name: Model Training CICD
permissions:
  id-token: write
  contents: write 
  
on:
  - push

jobs:
  run:
    runs-on: 
      - ubuntu-latest
    
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3

      # ✅ ADD THIS STEP (paste here)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ✅ ADD THIS STEP (your code goes here)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # end
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          python train_model.py

          echo "RF and LR Model Score" >report.md
          cat scores.txt >> report.md
          
          echo "Confusion Matrix & Feature Importance">report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md
     
          cat report.md report1.md >> combined_file.md
          cml comment create combined_file.md
